version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing Yarn..."
      - npm install -g yarn
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building React Application..."
      - yarn build
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  # include all files required to run application
  # we include only the static build files
  files:
    - "**/*"
   # reference directory where build file is located
  base-directory: "build"

cache:
  paths:
    - 'node_modules/**/*'
